// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1": {
            "post": {
                "description": "Create new user",
                "tags": [
                    "Posts"
                ],
                "summary": "registration",
                "parameters": [
                    {
                        "description": "query params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_controller_http_v1.registerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_controller_http_v1.registerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_controller_http_v1.errResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/category": {
            "get": {
                "description": "Get all categories",
                "tags": [
                    "Categories"
                ],
                "summary": "GetAllCategory",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_controller_http_v1.categoryListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_controller_http_v1.errResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/citizenship": {
            "get": {
                "description": "Get all citizenships",
                "tags": [
                    "Citizenships"
                ],
                "summary": "GetAllCitizenships",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/lg_internal_controller_http_v1.citizenshipListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/lg_internal_controller_http_v1.errResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/country": {
            "get": {
                "description": "Get all countries",
                "tags": [
                    "Countries"
                ],
                "summary": "GetAllCountries",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/lg_internal_controller_http_v1.countryListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/lg_internal_controller_http_v1.errResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/eduspeciality": {
            "get": {
                "description": "Get all eduspecialities",
                "tags": [
                    "Eduspecialities"
                ],
                "summary": "GetAllEduspecialities",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_controller_http_v1.eduspecialityListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_controller_http_v1.errResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/employment": {
            "get": {
                "description": "Get all employments",
                "tags": [
                    "Employments"
                ],
                "summary": "GetAllEmployments",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_controller_http_v1.employmentListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_controller_http_v1.errResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/project": {
            "get": {
                "description": "Get all projects",
                "tags": [
                    "Projects"
                ],
                "summary": "GetAllProjects",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/lg_internal_controller_http_v1.projectListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/lg_internal_controller_http_v1.errResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/specialization": {
            "get": {
                "description": "Get all specializations",
                "tags": [
                    "Specializations"
                ],
                "summary": "GetAllSpecializations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_controller_http_v1.specializationListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_controller_http_v1.errResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/university": {
            "get": {
                "description": "Get all universities",
                "tags": [
                    "Universities"
                ],
                "summary": "GetAllUniversities",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_controller_http_v1.universityListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_controller_http_v1.errResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_controller_http_v1.categoryDTO": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "internal_controller_http_v1.categoryListResponse": {
            "type": "object",
            "properties": {
                "categories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_controller_http_v1.categoryDTO"
                    }
                }
            }
        },
        "internal_controller_http_v1.citizenshipDTO": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "internal_controller_http_v1.citizenshipListResponse": {
            "type": "object",
            "properties": {
                "citizenships": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_controller_http_v1.citizenshipDTO"
                    }
                }
            }
        },
        "internal_controller_http_v1.countryDTO": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "internal_controller_http_v1.countryListResponse": {
            "type": "object",
            "properties": {
                "countries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_controller_http_v1.countryDTO"
                    }
                }
            }
        },
        "internal_controller_http_v1.eduspecialityDTO": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "internal_controller_http_v1.eduspecialityListResponse": {
            "type": "object",
            "properties": {
                "eduspecialities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_controller_http_v1.eduspecialityDTO"
                    }
                }
            }
        },
        "internal_controller_http_v1.employmentDTO": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "internal_controller_http_v1.employmentListResponse": {
            "type": "object",
            "properties": {
                "employments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_controller_http_v1.employmentDTO"
                    }
                }
            }
        },
        "internal_controller_http_v1.errResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "internal_controller_http_v1.projectDTO": {
            "type": "object",
            "properties": {
                "category_uuid": {
                    "type": "string"
                },
                "creator_uuid": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "is_visible": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "presentation_link": {
                    "type": "string"
                },
                "project_link": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "internal_controller_http_v1.projectListResponse": {
            "type": "object",
            "properties": {
                "projects": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_controller_http_v1.projectDTO"
                    }
                }
            }
        },
        "internal_controller_http_v1.registerRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "internal_controller_http_v1.registerResponse": {
            "type": "object",
            "properties": {
                "uuid": {
                    "type": "string"
                }
            }
        },
        "internal_controller_http_v1.specializationDTO": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "internal_controller_http_v1.specializationListResponse": {
            "type": "object",
            "properties": {
                "specializations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_controller_http_v1.specializationDTO"
                    }
                }
            }
        },
        "internal_controller_http_v1.universityDTO": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "internal_controller_http_v1.universityListResponse": {
            "type": "object",
            "properties": {
                "universities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_controller_http_v1.universityDTO"
                    }
                }
            }
        },
        "lg_internal_controller_http_v1.categoryDTO": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "lg_internal_controller_http_v1.categoryListResponse": {
            "type": "object",
            "properties": {
                "categories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/lg_internal_controller_http_v1.categoryDTO"
                    }
                }
            }
        },
        "lg_internal_controller_http_v1.citizenshipDTO": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "lg_internal_controller_http_v1.citizenshipListResponse": {
            "type": "object",
            "properties": {
                "citizenships": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/lg_internal_controller_http_v1.citizenshipDTO"
                    }
                }
            }
        },
        "lg_internal_controller_http_v1.countryDTO": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "lg_internal_controller_http_v1.countryListResponse": {
            "type": "object",
            "properties": {
                "countries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/lg_internal_controller_http_v1.countryDTO"
                    }
                }
            }
        },
        "lg_internal_controller_http_v1.eduspecialityDTO": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "lg_internal_controller_http_v1.eduspecialityListResponse": {
            "type": "object",
            "properties": {
                "eduspecialities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/lg_internal_controller_http_v1.eduspecialityDTO"
                    }
                }
            }
        },
        "lg_internal_controller_http_v1.employmentDTO": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "lg_internal_controller_http_v1.employmentListResponse": {
            "type": "object",
            "properties": {
                "employments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/lg_internal_controller_http_v1.employmentDTO"
                    }
                }
            }
        },
        "lg_internal_controller_http_v1.errResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "lg_internal_controller_http_v1.projectDTO": {
            "type": "object",
            "properties": {
                "category_uuid": {
                    "type": "string"
                },
                "creator_uuid": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "is_visible": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "presentation_link": {
                    "type": "string"
                },
                "project_link": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "lg_internal_controller_http_v1.projectListResponse": {
            "type": "object",
            "properties": {
                "projects": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/lg_internal_controller_http_v1.projectDTO"
                    }
                }
            }
        },
        "lg_internal_controller_http_v1.registerRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "lg_internal_controller_http_v1.registerResponse": {
            "type": "object",
            "properties": {
                "uuid": {
                    "type": "string"
                }
            }
        },
        "lg_internal_controller_http_v1.specializationDTO": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "lg_internal_controller_http_v1.specializationListResponse": {
            "type": "object",
            "properties": {
                "specializations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/lg_internal_controller_http_v1.specializationDTO"
                    }
                }
            }
        },
        "lg_internal_controller_http_v1.universityDTO": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "lg_internal_controller_http_v1.universityListResponse": {
            "type": "object",
            "properties": {
                "universities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/lg_internal_controller_http_v1.universityDTO"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Платформа для продвижения иновационных идей",
	Description:      "Хакатон \"Лига Цифровой Трансформации\"",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
