basePath: /
definitions:
  internal_controller_http_v1.categoryDTO:
    properties:
      name:
        type: string
      uuid:
        type: string
    type: object
  internal_controller_http_v1.categoryListResponse:
    properties:
      categories:
        items:
          $ref: '#/definitions/internal_controller_http_v1.categoryDTO'
        type: array
    type: object
  internal_controller_http_v1.citizenshipDTO:
    properties:
      name:
        type: string
      uuid:
        type: string
    type: object
  internal_controller_http_v1.citizenshipListResponse:
    properties:
      citizenships:
        items:
          $ref: '#/definitions/internal_controller_http_v1.citizenshipDTO'
        type: array
    type: object
  internal_controller_http_v1.countryDTO:
    properties:
      code:
        type: string
      name:
        type: string
      uuid:
        type: string
    type: object
  internal_controller_http_v1.countryListResponse:
    properties:
      countries:
        items:
          $ref: '#/definitions/internal_controller_http_v1.countryDTO'
        type: array
    type: object
  internal_controller_http_v1.eduspecialityDTO:
    properties:
      code:
        type: string
      name:
        type: string
      uuid:
        type: string
    type: object
  internal_controller_http_v1.eduspecialityListResponse:
    properties:
      eduspecialities:
        items:
          $ref: '#/definitions/internal_controller_http_v1.eduspecialityDTO'
        type: array
    type: object
  internal_controller_http_v1.employmentDTO:
    properties:
      name:
        type: string
      uuid:
        type: string
      value:
        type: string
    type: object
  internal_controller_http_v1.employmentListResponse:
    properties:
      employments:
        items:
          $ref: '#/definitions/internal_controller_http_v1.employmentDTO'
        type: array
    type: object
  internal_controller_http_v1.errResponse:
    properties:
      error:
        type: string
    type: object
  internal_controller_http_v1.projectDTO:
    properties:
      category_uuid:
        type: string
      creator_uuid:
        type: string
      description:
        type: string
      is_visible:
        type: string
      name:
        type: string
      presentation_link:
        type: string
      project_link:
        type: string
      uuid:
        type: string
    type: object
  internal_controller_http_v1.projectListResponse:
    properties:
      projects:
        items:
          $ref: '#/definitions/internal_controller_http_v1.projectDTO'
        type: array
    type: object
  internal_controller_http_v1.registerRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  internal_controller_http_v1.registerResponse:
    properties:
      uuid:
        type: string
    type: object
  internal_controller_http_v1.responseUUID:
    properties:
      uuid:
        type: string
    type: object
  internal_controller_http_v1.specializationDTO:
    properties:
      name:
        type: string
      uuid:
        type: string
      value:
        type: string
    type: object
  internal_controller_http_v1.specializationListResponse:
    properties:
      specializations:
        items:
          $ref: '#/definitions/internal_controller_http_v1.specializationDTO'
        type: array
    type: object
  internal_controller_http_v1.universityDTO:
    properties:
      name:
        type: string
      uuid:
        type: string
    type: object
  internal_controller_http_v1.universityListResponse:
    properties:
      universities:
        items:
          $ref: '#/definitions/internal_controller_http_v1.universityDTO'
        type: array
    type: object
  lg_internal_controller_http_v1.categoryDTO:
    properties:
      name:
        type: string
      uuid:
        type: string
    type: object
  lg_internal_controller_http_v1.categoryListResponse:
    properties:
      categories:
        items:
          $ref: '#/definitions/lg_internal_controller_http_v1.categoryDTO'
        type: array
    type: object
  lg_internal_controller_http_v1.citizenshipDTO:
    properties:
      name:
        type: string
      uuid:
        type: string
    type: object
  lg_internal_controller_http_v1.citizenshipListResponse:
    properties:
      citizenships:
        items:
          $ref: '#/definitions/lg_internal_controller_http_v1.citizenshipDTO'
        type: array
    type: object
  lg_internal_controller_http_v1.countryDTO:
    properties:
      code:
        type: string
      name:
        type: string
      uuid:
        type: string
    type: object
  lg_internal_controller_http_v1.countryListResponse:
    properties:
      countries:
        items:
          $ref: '#/definitions/lg_internal_controller_http_v1.countryDTO'
        type: array
    type: object
  lg_internal_controller_http_v1.eduspecialityDTO:
    properties:
      code:
        type: string
      name:
        type: string
      uuid:
        type: string
    type: object
  lg_internal_controller_http_v1.eduspecialityListResponse:
    properties:
      eduspecialities:
        items:
          $ref: '#/definitions/lg_internal_controller_http_v1.eduspecialityDTO'
        type: array
    type: object
  lg_internal_controller_http_v1.employmentDTO:
    properties:
      name:
        type: string
      uuid:
        type: string
      value:
        type: string
    type: object
  lg_internal_controller_http_v1.employmentListResponse:
    properties:
      employments:
        items:
          $ref: '#/definitions/lg_internal_controller_http_v1.employmentDTO'
        type: array
    type: object
  lg_internal_controller_http_v1.errResponse:
    properties:
      error:
        type: string
    type: object
  lg_internal_controller_http_v1.projectDTO:
    properties:
      category_uuid:
        type: string
      creator_uuid:
        type: string
      description:
        type: string
      is_visible:
        type: string
      name:
        type: string
      presentation_link:
        type: string
      project_link:
        type: string
      uuid:
        type: string
    type: object
  lg_internal_controller_http_v1.projectListResponse:
    properties:
      projects:
        items:
          $ref: '#/definitions/lg_internal_controller_http_v1.projectDTO'
        type: array
    type: object
  lg_internal_controller_http_v1.registerRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  lg_internal_controller_http_v1.registerResponse:
    properties:
      uuid:
        type: string
    type: object
  lg_internal_controller_http_v1.responseUUID:
    properties:
      uuid:
        type: string
    type: object
  lg_internal_controller_http_v1.specializationDTO:
    properties:
      name:
        type: string
      uuid:
        type: string
      value:
        type: string
    type: object
  lg_internal_controller_http_v1.specializationListResponse:
    properties:
      specializations:
        items:
          $ref: '#/definitions/lg_internal_controller_http_v1.specializationDTO'
        type: array
    type: object
  lg_internal_controller_http_v1.universityDTO:
    properties:
      name:
        type: string
      uuid:
        type: string
    type: object
  lg_internal_controller_http_v1.universityListResponse:
    properties:
      universities:
        items:
          $ref: '#/definitions/lg_internal_controller_http_v1.universityDTO'
        type: array
    type: object
host: localhost:9000
info:
  contact: {}
  description: Хакатон "Лига Цифровой Трансформации"
  title: Платформа для продвижения иновационных идей
  version: "1.0"
paths:
  /api/v1:
    post:
      description: Create new user
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/lg_internal_controller_http_v1.registerRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/lg_internal_controller_http_v1.registerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/lg_internal_controller_http_v1.errResponse'
      summary: registration
      tags:
      - Posts
  /api/v1/category:
    get:
      description: Get all categories
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/lg_internal_controller_http_v1.categoryListResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/lg_internal_controller_http_v1.errResponse'
      summary: GetAllCategory
      tags:
      - Categories
  /api/v1/citizenship:
    get:
      description: Get all citizenships
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_controller_http_v1.citizenshipListResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_controller_http_v1.errResponse'
      summary: GetAllCitizenships
      tags:
      - Citizenships
  /api/v1/country:
    get:
      description: Get all countries
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_controller_http_v1.countryListResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_controller_http_v1.errResponse'
      summary: GetAllCountries
      tags:
      - Countries
  /api/v1/eduspeciality:
    get:
      description: Get all eduspecialities
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/lg_internal_controller_http_v1.eduspecialityListResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/lg_internal_controller_http_v1.errResponse'
      summary: GetAllEduspecialities
      tags:
      - Eduspecialities
  /api/v1/employment:
    get:
      description: Get all employments
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_controller_http_v1.employmentListResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_controller_http_v1.errResponse'
      summary: GetAllEmployments
      tags:
      - Employments
  /api/v1/project:
    get:
      description: Get all projects
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_controller_http_v1.projectListResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_controller_http_v1.errResponse'
      summary: GetAllProjects
      tags:
      - Projects
    post:
      description: Create project
      parameters:
      - description: enter info project
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/internal_controller_http_v1.projectDTO'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/internal_controller_http_v1.responseUUID'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_controller_http_v1.errResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_controller_http_v1.errResponse'
      summary: CreateProject
      tags:
      - Projects
  /api/v1/project/{uuid}:
    get:
      description: Get project by UUID
      parameters:
      - description: Enter id book
        in: path
        name: uuid
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_controller_http_v1.projectDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_controller_http_v1.errResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/internal_controller_http_v1.errResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_controller_http_v1.errResponse'
      summary: GetProjectByUUID
      tags:
      - Projects
  /api/v1/specialization:
    get:
      description: Get all specializations
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_controller_http_v1.specializationListResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_controller_http_v1.errResponse'
      summary: GetAllSpecializations
      tags:
      - Specializations
  /api/v1/university:
    get:
      description: Get all universities
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_controller_http_v1.universityListResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_controller_http_v1.errResponse'
      summary: GetAllUniversities
      tags:
      - Universities
swagger: "2.0"
